### ISSUE TITLE
pytorch3d versions

### ISSUE THREAD

**Issue by Yacovitch** [PRBonn/LiDiff#9]
Hi whenever I tried to install pytorch3D by `pip3 install pytorch3d==0.7.4`, it gives following error,

`ERROR: Could not find a version that satisfies the requirement pytorch3d==0.7.4 (from versions: 0.1.1, 0.2.0, 0.2.5, 0.3.0)
ERROR: No matching distribution found for pytorch3d==0.7.4`

Do you have any idea what is the problem?

**Comment by nuneslu** [comment]
Hi! Actually, from pytorch3d, we just use the `chamfer_distance` loss, so you can try with an older version. In case it doesn't work, let me know, and we can try to figure it out.

**Comment by Yacovitch** [comment]
Thank you for your reply, I used pytorch3d version 0.3.0, and pip3 does not let me install later versions due to compatibility between Pytorch version. Do you have anyway to work around with it?

**Comment by nuneslu** [comment]
You could also install it from source. Which CUDA version are you using? From [here](https://github.com/facebookresearch/pytorch3d/releases/tag/v0.7.4) you can download it and to install it is the same as to install this repo, by using: pip3 install -e .

**Comment by nuneslu** [comment]
One further question, pytorch3d is only used in the refinement network. Did you manage to finish the training for the diffusion part?

**Comment by Yacovitch** [comment]
I am using CUDA version 11.4.

And yes, I was able to finish the training of the diffusion part. Now I am trying to train the refinement network.

I am tried your suggested method, but it gives me error. The error is quite long, so I am attaching only the last part of the error.

`    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
        env=env)
      File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/nas2/jacob/LiDiff/pytorch3d-0.7.4/setup.py", line 179, in <module>
        "": ["*.json"],
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 539, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
  Rolling back uninstall of pytorch3d
  Moving to /opt/conda/lib/python3.7/site-packages/pytorch3d-0.3.0.dist-info/
   from /opt/conda/lib/python3.7/site-packages/~ytorch3d-0.3.0.dist-info
  Moving to /opt/conda/lib/python3.7/site-packages/pytorch3d/
   from /opt/conda/lib/python3.7/site-packages/~ytorch3d
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/nas2/jacob/LiDiff/pytorch3d-0.7.4/setup.py'"'"'; __file__='"'"'/nas2/jacob/LiDiff/pytorch3d-0.7.4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

**Comment by nuneslu** [comment]
Try running pip3 install -e -v .

**Comment by Yacovitch** [comment]
It gives me the same error. Is it because I am trying to set up environment on JupyterLab?

**Comment by nuneslu** [comment]
The error doesn't seem to provide much information. Could you uninstall ninja and try running the command again? Ninja compile it in multithread and it gets hard to understand exactly where the error is.

**Comment by Yacovitch** [comment]
I created a separate environment and followed the instructions [https://github.com/facebookresearch/pytorch3d/releases/tag/v0.7.1](here), and it worked. It seems like some dependencies are missing. Also, based on your requirement it seems like pytorch3d 0.7.1 is more suitable.

**Comment by nuneslu** [comment]
Glad you managed to make it work. I will also update the requirements.txt since it seems that version 0.7.1 is easier to install with the other dependencies.

**Comment by Yacovitch** [comment]
Hi, I was able to make train_refine.py running!
One additional note is that pytorch-lightning gave me an error, and I fixed it by downgrading `setuptools` to 58.2.0. I found this solution from [https://github.com/Lightning-AI/pytorch-lightning/issues/12324#issuecomment-1067297952](url)

Now I am running `train_refine.py`, and it looks like it is stuck at Validation sanity check. Is it expected behaviour?

**Comment by nuneslu** [comment]
It is not expected. You can try setting num_val_sanity_check=0 in train_refine.py file so it skips the sanity check

**Comment by nuneslu** [comment]
Hi again, I figured out the problem with validation getting stuck, I was using the wrong collation function (some mistakes done during the refactoring of the code before releasing it). Sorry about that, you can pull the repo and get the correct version now, with the same collation used in the experiments reported in the paper.

**Comment by Yacovitch** [comment]
Thank you it is working now and thank you! I have another question. How long did it take for you to complete each epoch?

**Comment by nuneslu** [comment]
In our experiments, we used `batch_size: 8` and two GPUs, so it took around 5 hours per epoch. But I rerun it now with `batch_size: 2` in one GPU and it is taking around 20h per epoch. It takes long mainly because of the chamfer_distance computation.

**Comment by nuneslu** [comment]
No, it just needs 5 epochs to get the results from the paper

**Comment by nuneslu** [comment]
During development I let it train for longer to compare the results but with 5 epochs was already enough, that is why in the config there is `max_epoch: 100`

**Comment by Yacovitch** [comment]
Thank you very much! Lastly, if I want to check diffusion results without the refine model, which part of the `diff_completion_pipeline.py` should I look at?

**Comment by nuneslu** [comment]
You can use the provided refinement network weights and run the pipeline with your diffusion trained weights. In the pipeline output directory you should see two directories diff/ and refine/ the point clouds in diff/ will be the ones generated without the refinement

**Comment by Yacovitch** [comment]
Thank you very much for all the help!
